"""Add RAG v2 fields

Revision ID: 121d236efaf6
Revises: 5f63ba252eb9
Create Date: 2026-01-18 17:43:31.311646

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '121d236efaf6'
down_revision = '5f63ba252eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'books', ['book_id'], ['id'])
    op.add_column('reviews', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'embedding')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'book_id')
    op.drop_column('document_chunks', 'metadata_json')
    # ### end Alembic commands ###
