"""Add cascade deletes

Revision ID: 39696b903567
Revises: 121d236efaf6
Create Date: 2026-01-18 18:30:57.226220

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '39696b903567'
down_revision = '121d236efaf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
